# Site settings
title: Chehan Ratnasiri
keywords: chehanr,blog,web,site
description: My personal webspace.
baseurl: ""
url: "https://chehanr.xyz"
# Posts
permalink: /post/:year/:month/:day/:title/

name: Chehan Ratnasiri
email: chehan.rat@gmail.com
github:  chehanr
linkedin:  chehanr
twitter: chehanr
instagram:  chehanr
spotify:  22ipl2w2udlk4kcuary6xdeka
lastfm:  chehanr
disqus: chehanr

collections:
  projects:
    output: true
    permalink: /:collection/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
