title: Chehan Ratnasiri
keywords: chehanr, blog, web, site
description: My personal webspace.

baseurl: ""
url: "https://chehanr.com"

# Vars
name: Chehan Ratnasiri
email: chehan.rat@gmail.com
github: chehanr
linkedin: chehanr
twitter:
  username: chehanr
  card: summary
instagram: chehanr
spotify: 22ipl2w2udlk4kcuary6xdeka
lastfm: chehanr
disqus: chehanr
google_analytics: UA-56774080-3

collections:
  projects:
    output: true
    permalink: /:collection/:title/

# Build settings
environment: production
permalink: /post/:year/:month/:day/:title/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode/
  - "*.code-workspace"
